blank_issues_enabled: false
contact_links:
  - name: Help / Questions
    url: https://github.com/Requarks/wiki/discussions/categories/help-questions
    about: Ask the community for help on using or setting up Wiki.js
  - name: Report a Security Issue
    url: https://github.com/Requarks/wiki/security/policy
    about: Privately report security issues so they can be addressed quickly.
  - name: Errors / Bug Reports
    url: https://github.com/Requarks/wiki/discussions/categories/error-bug-report
    about: Create a discussion around the bug / error you're getting. If validated, a proper GitHub issue will be created so that it can be worked on.
  - name: Request a new feature / improvement
    url: https://feedback.js.wiki/wiki
    about: Submit ideas for new features or improvements.
