apiVersion: v1
kind: Service
metadata:
  name: {{include "wiki.fullname" .}}
  labels: {{- include "wiki.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{ default "80" .Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ default "443" .Values.service.httpsPort}}
      targetPort: http
      protocol: TCP
      name: https
  selector: {{- include "wiki.selectorLabels" . | nindent 4}}
