# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    container_name: wiki-db
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    container_name: wiki-adminer
    image: adminer:latest
    logging:
      driver: "none"
    ports:
      - "3001:8080"

  # solr:
  #   container_name: wiki-solr
  #   image: solr:7-alpine
  #   logging:
  #     driver: "none"
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - solr-data:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - wiki

  wiki:
    container_name: wiki-app
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ../..:/wiki
      - /wiki/node_modules
      - /wiki/.git


volumes:
  db-data:
  # solr-data:
