apiVersion: v2
name: wiki-js
version: '3.0.0'
appVersion: '2'
description: The most powerful and extensible open source Wiki software.
keywords:
  - wiki
  - documentation
  - knowledge base
  - docs
  - reference
  - editor
type: application
home: https://js.wiki
icon: https://cdn.js.wiki/images/wikijs-butterfly.svg
sources:
  - https://github.com/requarks/wiki
