apiVersion: v2
name: wiki
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.0.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
AppVersion: latest
description: The most powerful and extensible open source Wiki software.
keywords:
  - wiki
  - documentation
  - knowledge base
  - docs
  - reference
  - editor
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
dependencies:
  - name: postgresql
    version: 6.5.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
